
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: learnit_development

test:
  <<: *default
  database: learnit_test

production:
  <<: *default
  database: db/production.sqlite3
